// Mocks generated by Mockito 5.3.2 from annotations
// in news_clean_arch_app/test/features/show_news/presentation/news_cubit/news_cubit_test.dart.
// Do not manually edit this file.

// ignore_for_file: no_leading_underscores_for_library_prefixes
import 'dart:async' as _i5;

import 'package:dartz/dartz.dart' as _i3;
import 'package:mockito/mockito.dart' as _i1;
import 'package:news_clean_arch_app/core/failures_successes/failures.dart'
    as _i6;
import 'package:news_clean_arch_app/features/show_news/domain/entities/articles.dart'
    as _i7;
import 'package:news_clean_arch_app/features/show_news/domain/repositories/fetch_repo_contract.dart'
    as _i2;
import 'package:news_clean_arch_app/features/show_news/domain/usecases/fetch_news.dart'
    as _i4;

// ignore_for_file: type=lint
// ignore_for_file: avoid_redundant_argument_values
// ignore_for_file: avoid_setters_without_getters
// ignore_for_file: comment_references
// ignore_for_file: implementation_imports
// ignore_for_file: invalid_use_of_visible_for_testing_member
// ignore_for_file: prefer_const_constructors
// ignore_for_file: unnecessary_parenthesis
// ignore_for_file: camel_case_types
// ignore_for_file: subtype_of_sealed_class

class _FakeFetchRepo_0 extends _i1.SmartFake implements _i2.FetchRepo {
  _FakeFetchRepo_0(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

class _FakeEither_1<L, R> extends _i1.SmartFake implements _i3.Either<L, R> {
  _FakeEither_1(
    Object parent,
    Invocation parentInvocation,
  ) : super(
          parent,
          parentInvocation,
        );
}

/// A class which mocks [FetchNewsUsecase].
///
/// See the documentation for Mockito's code generation for more information.
class MockFetchNewsUsecase extends _i1.Mock implements _i4.FetchNewsUsecase {
  MockFetchNewsUsecase() {
    _i1.throwOnMissingStub(this);
  }

  @override
  _i2.FetchRepo get fetchRepo => (super.noSuchMethod(
        Invocation.getter(#fetchRepo),
        returnValue: _FakeFetchRepo_0(
          this,
          Invocation.getter(#fetchRepo),
        ),
      ) as _i2.FetchRepo);
  @override
  _i5.Future<_i3.Either<_i6.Failure, List<_i7.Articles>>> fetchNews(
          String? searchText) =>
      (super.noSuchMethod(
        Invocation.method(
          #fetchNews,
          [searchText],
        ),
        returnValue:
            _i5.Future<_i3.Either<_i6.Failure, List<_i7.Articles>>>.value(
                _FakeEither_1<_i6.Failure, List<_i7.Articles>>(
          this,
          Invocation.method(
            #fetchNews,
            [searchText],
          ),
        )),
      ) as _i5.Future<_i3.Either<_i6.Failure, List<_i7.Articles>>>);
}
